---
abstract: 'Basic HTTP authentication for Dancer web apps'
author:
  - 'Michal Wojciechowski <odyniec@cpan.org>'
build_requires:
  Authen::Passphrase: 0
  Pod::Readme: 0
  Pod::Select: 0
  Test::More: 0
configure_requires:
  Module::Build: 0.4
  Pod::Readme: 0
  Pod::Select: 0
dynamic_config: 1
generated_by: 'Module::Build version 0.4, CPAN::Meta::Converter version 2.113640'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Dancer-Plugin-Auth-Basic
provides:
  Dancer::Plugin::Auth::Basic:
    file: lib/Dancer/Plugin/Auth/Basic.pm
    version: 0.02
requires:
  Dancer: 1.307
  HTTP::Headers: 0
resources:
  license: http://dev.perl.org/licenses/
  repository: https://github.com/odyniec/Dancer-Plugin-Auth-Basic
version: 0.02
